# Generated by Django 4.0.5 on 2023-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceirizado',
            name='cargo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
